import type { Metadata } from "next";

import { AuthProvider } from "@/shared/contexts/auth-context";
import AuthGuard from "@/shared/gaurd/auth-guard";
import { SocketProvider } from "@/shared/contexts/socket-context";
import { SidebarProvider } from "@/components/ui/sidebar";
import FriendSidebar from "./components/friend-sidebar";

export const metadata: Metadata = {
  title: "Friends",
  description: "Generated by create next app",
};

export default function FriendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <AuthProvider>
        <AuthGuard>
          <SocketProvider>
            <SidebarProvider>
              <FriendSidebar />
              <div className="w-[100vw]">{children}</div>
            </SidebarProvider>
          </SocketProvider>
        </AuthGuard>
      </AuthProvider>
    </main>
  );
}
