import type { Metadata } from "next";

import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import AuthGuard from "@/shared/gaurd/auth-guard";
import { AuthProvider } from "@/shared/contexts/auth-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <AuthProvider>
        <AuthGuard>
          <SidebarProvider>
            <AppSidebar />
            <div className="w-[100vw]">{children}</div>
          </SidebarProvider>
        </AuthGuard>
      </AuthProvider>
    </main>
  );
}
