import type { Metadata } from "next";

import AppProvider from "@/shared/providers/app-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-[#f2f4f7]">
      <AppProvider>{children}</AppProvider>
    </main>
  );
}
