import FriendList from "@/app/(main)/message/friend-list";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Messages",
  description: "Generated by create next app",
};

export default function MessageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex w-full h-screen">
      <FriendList />
      <div className="flex flex-col h-screen w-full">{children}</div>
    </main>
  );
}
